// Get DOM elements
const analyzeButton = document.getElementById('analyzePage');
const copyButton = document.getElementById('copyButton');
const outputDiv = document.getElementById('output');
const copyFeedback = document.getElementById('copyFeedback');

// Store analysis data for copying
let currentAnalysis = null;
let pageMetadata = null;

// >>>>>>>>>>> CONFIGURATION <<<<<<<<<<<<
const CONFIG = {
  API_KEY: 'AIzaSyBTAQqxYxYHoBp1r2brVsAHGMeFmP24gRw', // Replace with your actual API key
  MODEL_NAME: 'gemini-2.0-flash',
  API_VERSION: 'v1beta'
};

// Function to show copy feedback
function showCopyFeedback() {
  copyFeedback.classList.add('show');
  setTimeout(() => {
    copyFeedback.classList.remove('show');
  }, 2000);
}

// Function to copy analysis to clipboard
async function copyToClipboard() {
  if (!currentAnalysis) return;

  const textToCopy = `
WISE Clinical Context Analysis
Source: ${pageMetadata.url}
Analysis Date: ${new Date().toLocaleString()}
${pageMetadata.searchContext ? `Search Context: ${pageMetadata.searchContext}\n` : ''}

SUMMARY:
${currentAnalysis.summary || 'N/A'}

MEDICAL CONDITIONS:
${currentAnalysis.conditions || 'N/A'}

MEDICATIONS:
${currentAnalysis.medications || 'N/A'}

DRUG INTERACTIONS:
${currentAnalysis.interactions || 'N/A'}

---
Generated by WISE Clinical Context Assistant
  `.trim();

  try {
    await navigator.clipboard.writeText(textToCopy);
    showCopyFeedback();
  } catch (err) {
    console.error('Failed to copy:', err);
    updateOutput(`<div class="error">Failed to copy to clipboard. Please try again.</div>`, true);
  }
}

// Function to update output
function updateOutput(content, isError = false, isSuccess = false) {
  outputDiv.innerHTML = content;
  outputDiv.classList.remove('error', 'success');
  if (isError) {
    outputDiv.classList.add('error');
  } else if (isSuccess) {
    outputDiv.classList.add('success');
  }
}

// Function to set loading state
function setLoading(isLoading) {
  analyzeButton.disabled = isLoading;
  analyzeButton.textContent = isLoading ? '⏳ Analyzing...' : '🔍 Analyze Page';
  copyButton.disabled = isLoading || !currentAnalysis;
}

// Function to extract search context from URL
function getSearchContext(url) {
  try {
    const urlObj = new URL(url);
    const searchParams = new URLSearchParams(urlObj.search);
    
    // Check common search parameters
    const searchTerms = searchParams.get('q') || 
                       searchParams.get('query') || 
                       searchParams.get('search') ||
                       searchParams.get('term');
    
    return searchTerms ? `results for "${searchTerms}"` : null;
  } catch (e) {
    return null;
  }
}

// Function to get page metadata
async function getPageMetadata() {
  try {
    let [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const searchContext = getSearchContext(tab.url);
    
    return {
      url: tab.url,
      title: tab.title,
      searchContext: searchContext,
      timestamp: new Date().toLocaleString()
    };
  } catch (error) {
    console.error('Error getting page metadata:', error);
    return {
      url: 'Unknown',
      title: 'Unknown',
      searchContext: null,
      timestamp: new Date().toLocaleString()
    };
  }
}

// Function to create metadata display
function createMetadataDisplay(metadata) {
  return `
    <div class="metadata">
      <div class="metadata-item"><strong>Source:</strong> ${metadata.url}</div>
      <div class="metadata-item"><strong>Page Title:</strong> ${metadata.title}</div>
      ${metadata.searchContext ? `<div class="metadata-item"><strong>Context:</strong> ${metadata.searchContext}</div>` : ''}
      <div class="metadata-item"><strong>Analyzed:</strong> ${metadata.timestamp}</div>
    </div>
  `;
}

// Function to create analysis display with special handling for non-medical content
function createAnalysisDisplay(analysis) {
  const hasMedicalContent = analysis.conditions && analysis.conditions !== 'N/A' && !analysis.conditions.toLowerCase().includes('no medical');
  const isNonMedicalPage = analysis.summary && (
    analysis.summary.toLowerCase().includes('news') || 
    analysis.summary.toLowerCase().includes('general') ||
    analysis.summary.toLowerCase().includes('not a medical')
  );

  let analysisHtml = `
    ${createMetadataDisplay(pageMetadata)}
    <div class="output-section">
      <div class="section-title"><span class="emoji">📋</span>Summary</div>
      <div class="section-content">${analysis.summary || 'N/A'}</div>
    </div>
    <div class="output-section">
      <div class="section-title"><span class="emoji">🏥</span>Medical Conditions</div>
      <div class="section-content">${analysis.conditions || 'N/A'}</div>
    </div>
    <div class="output-section">
      <div class="section-title"><span class="emoji">💊</span>Medications</div>
      <div class="section-content">${analysis.medications || 'N/A'}</div>
    </div>
    <div class="output-section">
      <div class="section-title"><span class="emoji">⚠️</span>Drug Interactions</div>
      <div class="section-content">${analysis.interactions || 'N/A'}</div>
    </div>
  `;

  // Add suggestion for non-medical pages or pages without medical conditions
  if (isNonMedicalPage || !hasMedicalContent) {
    analysisHtml += `
      <div class="suggestion-note">
        <strong>💡 Tip:</strong> This page appears to contain limited medical content. 
        For better clinical insights, try analyzing medical websites like Mayo Clinic, WebMD, or PubMed.
      </div>
      ${getWebsiteSuggestions()}
    `;
  }

  return analysisHtml;
}

// Function to handle different types of errors with user-friendly messages
function getFriendlyErrorMessage(error) {
  console.error("Raw error:", error);
  
  // Handle JSON parsing errors (common when AI doesn't return proper JSON)
  if (error.message.includes('Unexpected token') || error.message.includes('JSON')) {
    return {
      message: "The content on this page may not be suitable for medical analysis. Please try a medical website.",
      isMedicalContentIssue: true
    };
  }
  
  // Handle browser pages
  if (error.message.includes('Cannot analyze browser pages')) {
    return {
      message: "Cannot analyze this browser page. Please navigate to a medical/diseases information website.",
      isMedicalContentIssue: true
    };
  }
  
  // Handle insufficient text
  if (error.message.includes('not contain enough text')) {
    return {
      message: "This page doesn't contain enough text content for analysis. Please try a different medical website.",
      isMedicalContentIssue: true
    };
  }
  
  // Handle API key errors
  if (error.message.includes('API key') || error.message.includes('401') || error.message.includes('403')) {
    return {
      message: "Authentication issue. Please check your API configuration.",
      isMedicalContentIssue: false
    };
  }
  
  // Handle other API errors
  if (error.message.includes('API') || error.message.includes('HTTP')) {
    return {
      message: "Temporary service issue. Please try again in a moment.",
      isMedicalContentIssue: false
    };
  }
  
  // Default error message
  return {
    message: "An unexpected error occurred. Please try again or try a different webpage.",
    isMedicalContentIssue: false
  };
}

// Function to create helpful website suggestions
function getWebsiteSuggestions() {
  return `
    <div class="output-section">
      <div class="section-title"><span class="emoji">🌐</span>Recommended Medical Websites</div>
      <div class="section-content">
        <strong>For Best Results:</strong><br>
        • <a href="https://www.mayoclinic.org/diseases-conditions" target="_blank">Mayo Clinic</a><br>
        • <a href="https://www.webmd.com/a-to-z-guides/common-topics" target="_blank">WebMD A-Z</a><br>
        • <a href="https://medlineplus.gov/healthtopics.html" target="_blank">MedlinePlus</a><br>
        • <a href="https://www.ncbi.nlm.nih.gov/pmc/" target="_blank">PubMed Central</a><br>
        • <a href="https://www.who.int/health-topics" target="_blank">WHO Health Topics</a><br>
        • <a href="https://www.apollohospitals.com/patient-care/health-and-lifestyle/diseases-and-conditions/" target="_blank">Apollo Hospitals</a>
      </div>
    </div>
  `;
}

// API call function
async function callGeminiAPI(pageText) {
  const prompt = `
    You are a helpful clinical assistant. Analyze the following webpage text and provide:
    1. A concise summary (1-2 bullet points)
    2. Any mentioned medical conditions (list them or say "N/A" if none)
    3. Any mentioned medications (list them or say "N/A" if none)
    4. Any potential drug interactions (list them or say "N/A" if none/no multiple medications)
    
    If the content is clearly non-medical (news, sports, entertainment, etc.), provide a brief summary indicating this is not medical content, and use "N/A" for medical fields.
    
    Return ONLY valid JSON with this exact structure:
    {
      "summary": "your summary here",
      "conditions": "list or N/A",
      "medications": "list or N/A", 
      "interactions": "list or N/A"
    }
    
    Webpage Text: ${pageText.substring(0, 12000)}
  `;

  const requestData = {
    contents: [{
      parts: [{ text: prompt }]
    }]
  };

  const API_URL = `https://generativelanguage.googleapis.com/${CONFIG.API_VERSION}/models/${CONFIG.MODEL_NAME}:generateContent?key=${CONFIG.API_KEY}`;

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestData)
    });

    if (!response.ok) {
      const errorDetail = await response.text();
      throw new Error(`HTTP Error! Status: ${response.status}, Details: ${errorDetail}`);
    }

    const data = await response.json();
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("API response contains no 'candidates'. This might be due to safety filters.");
    }

    const candidate = data.candidates[0];
    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error("API candidate missing 'content' or 'parts'.");
    }

    const responseText = candidate.content.parts[0].text;
    console.log("Raw API response:", responseText);

    // Extract JSON from response
    const jsonMatch = responseText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
    let jsonString = jsonMatch ? jsonMatch[1] : responseText;

    // Clean the JSON string
    jsonString = jsonString.trim();
    if (jsonString.startsWith('{') && jsonString.endsWith('}')) {
      return JSON.parse(jsonString);
    } else {
      throw new Error("API response is not valid JSON");
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    
    // Check for JSON parsing errors specifically
    if (error instanceof SyntaxError) {
      throw new Error("Unexpected token - response is not valid JSON");
    }
    
    throw new Error(`Failed to get analysis from AI: ${error.message}`);
  }
}

// Event listeners
analyzeButton.addEventListener('click', async () => {
  setLoading(true);
  copyButton.disabled = true;

  try {
    let [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    
    if (tab.url.startsWith('chrome://') || tab.url.startsWith('about:')) {
      throw new Error('Cannot analyze this browser page. Please navigate to a medical/diseases information website.');
    }

    // Get page metadata first
    pageMetadata = await getPageMetadata();

    const injectionResults = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: () => document.body.innerText
    });

    const pageText = injectionResults[0].result;
    
    if (!pageText || pageText.trim().length < 50) {
      throw new Error('Page does not contain enough text to analyze. Please try a different medical website.');
    }

    const analysis = await callGeminiAPI(pageText);
    currentAnalysis = analysis;

    // Ensure all fields have proper values
    currentAnalysis.summary = currentAnalysis.summary || 'N/A';
    currentAnalysis.conditions = currentAnalysis.conditions || 'N/A';
    currentAnalysis.medications = currentAnalysis.medications || 'N/A';
    currentAnalysis.interactions = currentAnalysis.interactions || 'N/A';

    updateOutput(createAnalysisDisplay(analysis), false, true);
    copyButton.disabled = false;

  } catch (error) {
    console.error("Error in button click handler:", error);
    
    const friendlyError = getFriendlyErrorMessage(error);
    let errorHtml = `
      <div class="output-section">
        <div class="section-title"><span class="emoji">❌</span>Analysis Failed</div>
        <div class="section-content">${friendlyError.message}</div>
      </div>
    `;
    
    // Add website suggestions for medical content issues
    if (friendlyError.isMedicalContentIssue) {
      errorHtml += getWebsiteSuggestions();
    }
    
    updateOutput(errorHtml, true);
    currentAnalysis = null;
  } finally {
    setLoading(false);
  }
});

copyButton.addEventListener('click', copyToClipboard);

// Initialize with website suggestions
updateOutput(`
  <div class="output-section">
    <div class="section-title"><span class="emoji">👋</span>Ready to Analyze</div>
    <div class="section-content">Navigate to a medical webpage and click "Analyze Page" to get clinical insights.</div>
  </div>
  ${getWebsiteSuggestions()}
`);